# Importing python libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("C:/Users/hp/Downloads/Sample - Superstore.csv" , encoding = "ISO-8859-1")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

# Finding Total number of products

In [5]:
number_of_product = df["Product Name"].value_counts()
number_of_product

Product Name
Staple envelope                                                                        48
Staples                                                                                46
Easy-staple paper                                                                      46
Avery Non-Stick Binders                                                                20
Staples in misc. colors                                                                19
                                                                                       ..
Boston 1900 Electric Pencil Sharpener                                                   1
RCA ViSYS 25423RE1 Corded phone                                                         1
Canon Color ImageCLASS MF8580Cdw Wireless Laser All-In-One Printer, Copier, Scanner     1
Newell 342                                                                              1
Eldon Jumbo ProFile Portable File Boxes Graphite/Black                                  1
Name: count, Length: 1850, dtype: int64

# Finding Total number of Cities

In [6]:
number_of_cities = df["City"].value_counts()
number_of_cities

City
New York City      915
Los Angeles        747
Philadelphia       537
San Francisco      510
Seattle            428
                  ...
Glenview             1
Missouri City        1
Rochester Hills      1
Palatine             1
Manhattan            1
Name: count, Length: 531, dtype: int64

In [7]:
number_of_region = df["Region"].value_counts()
number_of_region

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

# Finding total discounts given to every customer

In [8]:
discounts = df["Discount"].value_counts()
discounts

Discount
0.00    4798
0.20    3657
0.70     418
0.80     300
0.30     227
0.40     206
0.60     138
0.10      94
0.50      66
0.15      52
0.32      27
0.45      11
Name: count, dtype: int64

# Finding total number of discounts given to every customer

In [9]:
customer_discount=df.groupby("Customer Name")["Discount"].sum()
customer_discount

Customer Name
Aaron Bergman         0.40
Aaron Hawkins         1.00
Aaron Smayling        3.55
Adam Bellavance       0.80
Adam Hart             2.70
                      ...
Xylona Preis          1.30
Yana Sorensen         0.60
Yoseph Carroll        0.60
Zuschuss Carroll      7.90
Zuschuss Donatelli    1.00
Name: Discount, Length: 793, dtype: float64

# CUSTOMERS WITH HIGHEST DISCOUNT

In [10]:
top_customer= customer_discount.sort_values(ascending = False).head(5)
top_customer

Customer Name
Zuschuss Carroll       7.9
William Brown          7.6
Chloris Kastensmidt    7.5
Erin Ashbrook          7.5
Lena Cacioppo          7.2
Name: Discount, dtype: float64

# Finding highest sold categories

In [11]:
df["Category"].value_counts().sort_values(ascending = False).head()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

# Finding highest sold Sub-Categories

In [12]:
df["Sub-Category"].value_counts().sort_values(ascending = False).head()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Name: count, dtype: int64

# Finding most loyal customer

In [13]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [14]:
customer_stats = df.groupby("Customer Name").agg({"Order Date": "nunique","Sales":"sum", "Discount":"mean"}).reset_index()

In [15]:
customer_stats.rename(columns={"Order Date":"Order_Frequency","Sales":"Total_Sales","Profit":"Total_Profit","Discount":"Avg_Discount"}, inplace=True)

In [16]:
loyal_customers = customer_stats.sort_values(by=["Order_Frequency","Total_Sales"],ascending=[False,False]).head(10)
loyal_customers

           Customer Name  Order_Frequency  Total_Sales  Avg_Discount
259           Emily Phan               17    5478.0608      0.197419
791     Zuschuss Carroll               13    8025.7070      0.254839
381           Joel Eaton               13    6760.8150      0.145652
663        Sally Hughsby               13    3406.8395      0.136207
145  Chloris Kastensmidt               13    3154.8550      0.234375
586      Patrick Gardner               13    3086.9070      0.169231
267        Erin Ashbrook               13    2846.7050      0.300000
441         Ken Lonsdale               12   14175.2290      0.200000
169          Clay Ludtke               12   10880.5460      0.114286
249         Edward Hooks               12   10310.8800      0.071875

# finding out on which day did the Business flourish

In [23]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [24]:
profit_by_date = df.groupby("Order Date")["Profit"].sum().reset_index()

In [25]:
max_profit_date = profit_by_date.loc[profit_by_date["Profit"].idxmax()]

In [26]:
print("Date with highest profit:",max_profit_date["Order Date"])
print("Profit amount:", max_profit_date["Profit"])

Date with highest profit: 2016-10-02 00:00:00
Profit amount: 8738.797100000002

# Finding customes sales and profit ratio

In [31]:
customer_profit = df.groupby("Customer Name")[["Sales","Profit"]].sum().reset_index()

In [32]:
customer_profit = customer_profit.sort_values(by="Profit",ascending=False)

In [33]:
print(customer_profit.head(10))

            Customer Name      Sales     Profit
730          Tamara Chand  19052.218  8981.3239
622          Raymond Buch  15117.339  6976.0959
671          Sanjit Chand  14142.334  5757.4119
334          Hunter Lopez  12873.298  5622.4292
6           Adrian Barton  14473.571  5444.8055
757          Tom Ashbrook  14595.620  4703.7883
157  Christopher Martinez   8954.020  3899.8904
431         Keith Dawkins   8181.256  3038.6254
35            Andy Reiter   6608.448  2884.6208
194         Daniel Raglin   8350.868  2869.0760

# Finding Profit and sales based on region

In [34]:
region_profit = df.groupby("Region")[["Sales","Profit"]].sum().reset_index()

In [50]:
region_profit = region_profit.sort_values(by = "Profit" , ascending = False)

In [51]:
print(region_profit.head())

    Region        Sales       Profit
3     West  725457.8245  108418.4489
1     East  678781.2400   91522.7800
2    South  391721.9050   46749.4303
0  Central  501239.8908   39706.3625

# Finding Profit and sales based on States

In [47]:
state_profit = df.groupby("State")[["Sales","Profit"]].sum().reset_index()

In [52]:
state_profit = state_profit.sort_values(by = "Profit" , ascending = False)

In [53]:
print(state_profit.head())

         State        Sales      Profit
3   California  457687.6315  76381.3871
30    New York  310876.2710  74038.5486
45  Washington  138641.2700  33402.6517
20    Michigan   76269.6140  24463.1876
44    Virginia   70636.7200  18597.9504

# Finding which Segment is profitable more

In [56]:
segment_profit = df.groupby("Segment")[["Sales","Profit"]].sum().reset_index()

In [57]:
segment_profit = segment_profit.sort_values(by = "Profit" , ascending = False)

In [58]:
print(segment_profit.head())

       Segment         Sales       Profit
0     Consumer  1.161401e+06  134119.2092
1    Corporate  7.061464e+05   91979.1340
2  Home Office  4.296531e+05   60298.6785

# Finding which Product is more profitabel

In [64]:
product_profit = df.groupby("Product Name")[["Sales","Profit"]].sum().reset_index()

In [65]:
product_profit = product_profit.sort_values(by = "Profit" , ascending = False)

In [66]:
print(product_profit.head())

                                          Product Name      Sales      Profit
404              Canon imageCLASS 2200 Advanced Copier  61599.824  25199.9280
650  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384   7753.0390
805               Hewlett Packard LaserJet 3310 Copier  18839.686   6983.8836
400                 Canon PC1060 Personal Laser Copier  11619.834   4570.9347
787  HP Designjet T520 Inkjet Large Format Printer ...  18374.895   4094.9766

# Finding best seller and profitable Category and Sub Category

In [75]:
category_summary = df.groupby("Category")[["Sales","Profit"]].sum().reset_index()

In [76]:
best_seller_category = category_summary.loc[category_summary["Sales"].idxmax()]

In [77]:
best_profit_category= category_summary.loc[category_summary["Profit"].idxmax()]

In [78]:
print("Best Seller Category:", best_seller_category["Category"],"Sales:", best_seller_category["Sales"])
print("Most profitable Category:","Profit:", best_seller_category["Category"],"Profit:", best_profit_category ["Profit"])

Best Seller Category: Technology Sales: 836154.033
Most profitable Category: Profit: Technology Profit: 145454.9481

# Finding Profit based on Category and Sub-Category

In [80]:
sdf = df.groupby("Category")[["Profit","Sales"]].sum().reset_index()

In [85]:
sdf = sdf.sort_values(by ="Profit", ascending = False)
sdf

          Category       Profit        Sales
2       Technology  145454.9481  836154.0330
1  Office Supplies  122490.8008  719047.0320
0        Furniture   18451.2728  741999.7953

In [82]:
ss = df.groupby("Sub-Category")[["Profit","Sales"]].sum().reset_index()

In [86]:
ss = ss.sort_values(by ="Profit", ascending = False)
ss.head()

   Sub-Category      Profit       Sales
6       Copiers  55617.8249  149528.030
13       Phones  44515.7306  330007.054
0   Accessories  41936.6357  167380.318
12        Paper  34053.5693   78479.206
3       Binders  30221.7633  203412.733

# Profitable Category by region

In [92]:
region = df.groupby("Region")[["Category","Profit"]].sum().reset_index()

In [93]:
region = region.sort_values( by="Profit", ascending = False)
region.head()

    Region                                           Category       Profit
3     West  Office SuppliesFurnitureOffice SuppliesTechnol...  108418.4489
1     East  FurnitureFurnitureOffice SuppliesFurnitureOffi...   91522.7800
2    South  FurnitureFurnitureFurnitureOffice SuppliesOffi...   46749.4303
0  Central  Office SuppliesOffice SuppliesOffice SuppliesO...   39706.3625

# Profitable ship mode by region

In [95]:
proregion = df.groupby("Region")[["Profit","Ship Mode"]].sum().reset_index()

In [96]:
proregion = proregion.sort_values(by = "Profit" , ascending= False)
proregion.head()

    Region       Profit                                          Ship Mode
3     West  108418.4489  Second ClassStandard ClassStandard ClassStanda...
1     East   91522.7800  Second ClassStandard ClassStandard ClassStanda...
2    South   46749.4303  Second ClassSecond ClassStandard ClassStandard...
0  Central   39706.3625  Standard ClassStandard ClassStandard ClassStan...

# Best seller day by category

In [99]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [100]:
category_day_sales = df.groupby(["Category", "Order Date"])["Sales"].sum().reset_index()

In [103]:
best_seller_day = category_day_sales.loc[category_day_sales.groupby("Category")["Sales"].idxmax()]
print(best_seller_day)

             Category Order Date      Sales
326         Furniture 2015-09-17  10006.174
1073  Office Supplies 2014-09-23  10142.354
2058       Technology 2014-03-18  24739.748

# Best seller month by category

In [104]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [105]:
df["YearMonth"] = df["Order Date"].dt.to_period("M")

In [106]:
category_month_sales = df.groupby(["Category", "YearMonth"])["Sales"].sum().reset_index()

In [107]:
best_seller_month = category_month_sales.loc[category_month_sales.groupby("Category")["Sales"].idxmax()]
print(best_seller_month)

            Category YearMonth      Sales
46         Furniture   2017-11  37056.715
83   Office Supplies   2016-12  37997.566
142       Technology   2017-11  49918.773

# Best seller sub-Category by Segment

In [108]:
sub = df.groupby("Sub-Category")["Segment"].sum().reset_index()

In [109]:
sub = sub.sort_values(by = "Segment" , ascending = False)

In [111]:
print("Best Seller Sub-Category by Segment")
sub.head()

Best Seller Sub-Category by Segment

   Sub-Category                                            Segment
8     Fasteners  CorporateConsumerCorporateConsumerConsumerCons...
10       Labels  CorporateConsumerConsumerConsumerCorporateCorp...
1    Appliances  ConsumerHome OfficeCorporateCorporateCorporate...
7     Envelopes  ConsumerHome OfficeCorporateConsumerConsumerCo...
12        Paper  ConsumerHome OfficeConsumerConsumerConsumerCon...

# Correlation Analysis